export const messageConstant = {
    CONNECTION_ERROR: 'Error while connecting to database!',
    DB_CONNECTED: 'MongoDB database connected!',
    APP_STARTED: 'Application Running!',
    BOOK_NOT_FOUND: 'Book not found!',
    USER_NOT_FOUND: 'User not found!',
    USER_NOT_EXISTS: 'User not exists!',
    USER_DELETED_SOFT: 'User deleted(soft)',
    USER_DELETED_HARD: 'User deleted(hard)',
    ADMIN_NOT_FOUND: 'Admin not found!',
    ERROR_SENDING_MAIL: 'Error sending mail!',
    ERROR_SIGNING_USER: 'Error signing user!',
    ERROR_CREATING_BOOK: 'Error creating book!',
    ERROR_ASSIGNING_BOOK: 'Error assigning book!',
    ERROR_UPDATING_BOOK: 'Error updating book!',
    ERROR_UPDATING_USER: 'Error updating user!',
    ERROR_LISTING_BOOK: 'Error listing book!',
    ERROR_LISTING_USER: 'Error listing user!',
    ERROR_DELETING_USER: 'Error deleting user!',
    ERROR_DELETING_BOOK: 'Error deleting book!',
    ERROR_UPDATING_PROFILE: 'Error updating profile',
    ERROR_LOGGING_HISTORY: 'Error while logging history',
    BOOK_DELETED_SOFT: 'Book deleted(Soft)!',
    BOOK_DELETED_HARD: 'Book deleted(Hard)!',
    BOOK_ALREADY_EXISTS: 'Book already exists!',
    BOOK_NOT_EXISTS: 'Book does not exists!',
    BOOK_OUT_OF_STOCK: 'Book out of stock',
    BOOK_LIMIT_EXCEEDED: 'User cannot have more than 5 books issued',
    BOOK_NOT_ISSUED: 'Book is not issued to this user!',
    SUBMIDATE_INVALID: 'submit date is invalid, kindly check!',
    SUBMIT_DATE_INVALID: 'Submit date cannot be before to the issue date',
    OUTSTANDING_DUE_CHARGES:
        'User has outstanding due charges. Please clear them before issuing a book.',
    ISSUE_DATE_INVALID: 'Issue date should not be of past',
    INVALID_AGE: 'Age must be 12 years old!',
    REVIEW_ALREADY_EXIST: 'Review done already!',
    RATING_ALREADY_EXIST: 'Rating done already!',
    BOOK_HISTORY_NOT_FOUND: 'Book history not found!',
    NO_ISSUED_BOOK_FOUND: 'No issued books found!',
    INVALID_PAGE_NUMBER: 'Page number must be less than total pages',
    INVALID_ACCESS_TOKEN: 'Invalid access token',
    INVALID_REFRESH_TOKEN: 'Invalid refresh token',
    INVALID_HEADER: 'Invalid header',
    INVALID_DATE_FORMAT: 'Invalid date format',
    CANNOT_ISSUE_SAME_BOOK: 'User cannot issue the same book again!',
    INVALID_TOKEN_TYPE: 'Invalid token type',
    INVALID_RESET_TOKEN: 'Invalid reset token',
    ERROR_UPDATING_DUE_CHARGES_IN_USER: 'Error while updating due charges in user',
};
